### ISSUE TITLE
Error in on_load (Windows 10, ST3)

### ISSUE THREAD

**Issue by JoBrad** [DavidGerva/LockTab-Sublime-Plugin#1]
Hi, 
I installed your plugin on my Win10 x64 box, in ST3, I get this error:
Traceback (most recent call last):

> `File "D:\Program Files\Sublime Text\3\sublime_plugin.py", line 208, in on_load
>     callback.on_load(v)
>   File "LockTab in C:\Users\<my_user_name>\AppData\Roaming\Sublime Text 3\Installed Packages\LockTab.sublime-package", line 141, in on_load
> AttributeError: 'KeyBindingListener' object has no attribute 'visibleRegion'
> ignored packages updated to: ["LockTab", "Vintage"]`

I haven't done any further troubleshooting at this point, but thought you might want to know. Thanks.

**Comment by evandrocoan** [comment]
There is also this popping when you unlock the tab and breaking completely the package:

![image](https://cloud.githubusercontent.com/assets/5332158/20186897/ff2f85fe-a758-11e6-83f0-b12dd397980a.png)

```
Package Control: Skipping automatic upgrade, last run at 2016-11-10 15:01:42, next run at 2016-11-10 16:01:42 or after
reloading settings Packages/User/LockTab.sublime-settings
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 389, in run_callback
    expr()
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 428, in <lambda>
    run_callback('on_load', callback, lambda: callback.on_load(v))
  File "LockTab in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\LockTab.sublime-package", line 141, in on_load
AttributeError: 'KeyBindingListener' object has no attribute 'visibleRegion'
00
``
```
